
clear all; close all; startup;

% DJF 1998-2012 
% plot contour map of 5th percentile decadal trends (3rd col) from AR1
% ran with Standard Deviation (1st col) and lag-1 autocorrelation (2nd col). 
stdrho5th=[
1.3 0.2 -1.52;
1.5 0.2 -1.74;
1.7 0.2 -2.0;
2.0 0.2 -2.3;
2.3 0.2 -2.7;
2.5 0.2 -2.86;
1.3 0.3 -1.66;
1.5 0.3 -1.81;
1.7 0.3 -2.14;
2.0 0.3 -2.48;
2.3 0.3 -2.86;
2.5 0.3 -3.08;
1.3 0.4 -1.8;
1.5 0.4 -2.05;
1.7 0.4 -2.23;
2.0 0.4 -2.62;
2.3 0.4 -3.0;
2.5 0.4 -3.23;
1.3 0.5 -1.86;
1.5 0.5 -2.15;
1.7 0.5 -2.44;
2.0 0.5 -2.82;
2.3 0.5 -3.32;
2.5 0.5 -3.52;
];

[X,Y]=meshgrid(stdrho5th(1:6,1),stdrho5th(1:6:end,2));
Z=reshape(stdrho5th(:,3),6,4);
scrsz = get(0,'ScreenSize');
%[left, bottom, width, height]
figure('Position',[1 scrsz(4)/2 scrsz(3)/2.2 scrsz(4)/1.7]);
figure(1),clf
contourf(X,Y,Z',9);
hold on;
%plot isoline for observed trend
[C,h] = contour(X,Y,Z',[-2.09 -2.09],'r');
h.LineWidth = 8.0;
hold on;
%plot isoline for 5th prctl trend generated by observed rho and sigma
[C,h] = contour(X,Y,Z',[-1.72 -1.72],'b--');
h.LineWidth = 8.0;
hold on;
%plot marker for observed sigma, rho.
plot(1.48,0.2,'b.','MarkerSize',80,'LineWidth',16.0)
hold off;
axis([1.3 2.5 0.2 0.5])
set(gca,'Xtick',[1.3 1.5 1.7 1.9 2.1 2.3 2.5]);
colorbar;
title('5th prctl trends on \rho_{-1}-\sigma plane');
xlabel('\sigma');
ylabel('\rho_{-1}');